import Head from 'next/head'
import { Montserrat } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { GetServerSideProps } from 'next'
import { app } from '@/lib/firebase'
import { User, getAuth } from 'firebase/auth'
import { useEffect, useState } from 'react'
const montserrat = Montserrat({
  subsets: ["latin"]
})

export default function Home() {
  const [user, setUser] = useState<null | User>()
  const auth = getAuth(app);
  auth.onAuthStateChanged(async user => {
    setUser(user)
    if (user) {
      console.log(await user.getIdToken())
      console.log(user)
    }
  });
  // useEffect(() => {
  //   (async () => {
  //     console.log(await user?.getIdToken())
  //   })
  // }, [user])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={montserrat.className}>
        {JSON.stringify(user)}
        <button onClick={async () => console.log(await user?.getIdToken())}>click</button>
      </main>
    </>
  )
}
